export const jobs = [
  {
    id: 'g01',
    company: 'Google',
    role: 'Frontend Developer',
    location: 'Bangalore, IN',
    salary: '₹18–28 LPA',
    type: 'Full-time',
    eligibility: '0–3 years, React + TypeScript',
    applicationDates: 'Sep 15 – Oct 15, 2025',
    qualification: 'B.E/B.Tech in CS or related',
    applyUrl: 'https://careers.google.com/',
  },
  {
    id: 'g02',
    company: 'Google',
    role: 'Data Analyst Intern',
    location: 'Hyderabad, IN',
    salary: '₹50,000/month',
    type: 'Internship',
    eligibility: 'Final-year students',
    applicationDates: 'Oct 01 – Nov 10, 2025',
    qualification: 'Bachelors in STEM',
    applyUrl: 'https://careers.google.com/',
  },
  {
    id: 'g03',
    company: 'Google',
    role: 'Backend Engineer',
    location: 'Bangalore, IN',
    salary: '₹20–32 LPA',
    type: 'Full-time',
    eligibility: '2–6 years, Go/Java, Distributed Systems',
    applicationDates: 'Sep 18 – Oct 28, 2025',
    qualification: 'B.E/B.Tech/M.Tech',
    applyUrl: 'https://careers.google.com/',
  },
  {
    id: 'g04',
    company: 'Google',
    role: 'ML Engineer',
    location: 'Hyderabad, IN',
    salary: '₹24–38 LPA',
    type: 'Full-time',
    eligibility: '3–7 years, Python, TensorFlow',
    applicationDates: 'Sep 20 – Nov 05, 2025',
    qualification: 'Masters preferred',
    applyUrl: 'https://careers.google.com/',
  },
  {
    id: 'ms01',
    company: 'Microsoft',
    role: 'Software Engineer',
    location: 'Hyderabad, IN',
    salary: '₹22–35 LPA',
    type: 'Full-time',
    eligibility: '1–5 years, DSA + System Design',
    applicationDates: 'Sep 10 – Oct 20, 2025',
    qualification: 'B.E/B.Tech/M.Tech',
    applyUrl: 'https://careers.microsoft.com/',
  },
  {
    id: 'ms02',
    company: 'Microsoft',
    role: 'Product Manager Intern',
    location: 'Bengaluru, IN',
    salary: '₹70,000/month',
    type: 'Internship',
    eligibility: 'MBA students',
    applicationDates: 'Sep 25 – Nov 05, 2025',
    qualification: 'MBA (in progress)',
    applyUrl: 'https://careers.microsoft.com/',
  },
  {
    id: 'ms03',
    company: 'Microsoft',
    role: 'Cloud Engineer (Azure)',
    location: 'Noida, IN',
    salary: '₹18–28 LPA',
    type: 'Full-time',
    eligibility: '2–5 years, Azure, Kubernetes',
    applicationDates: 'Sep 22 – Nov 01, 2025',
    qualification: 'B.E/B.Tech',
    applyUrl: 'https://careers.microsoft.com/',
  },
  {
    id: 'ms04',
    company: 'Microsoft',
    role: 'UI Engineer',
    location: 'Hyderabad, IN',
    salary: '₹16–26 LPA',
    type: 'Full-time',
    eligibility: '2–4 years, React/Fluent UI',
    applicationDates: 'Sep 15 – Oct 30, 2025',
    qualification: 'B.E/B.Tech',
    applyUrl: 'https://careers.microsoft.com/',
  },
  {
    id: 'amz01',
    company: 'Amazon',
    role: 'Backend Developer',
    location: 'Chennai, IN',
    salary: '₹16–30 LPA',
    type: 'Full-time',
    eligibility: '2–6 years, Java/Spring or Node.js',
    applicationDates: 'Sep 12 – Oct 31, 2025',
    qualification: 'B.E/B.Tech',
    applyUrl: 'https://www.amazon.jobs/',
  },
  {
    id: 'amz02',
    company: 'Amazon',
    role: 'SDE Intern',
    location: 'Pune, IN',
    salary: '₹60,000/month',
    type: 'Internship',
    eligibility: 'Pre-final year students',
    applicationDates: 'Sep 20 – Nov 20, 2025',
    qualification: 'B.E/B.Tech (in progress)',
    applyUrl: 'https://www.amazon.jobs/',
  },
  {
    id: 'amz03',
    company: 'Amazon',
    role: 'Frontend Engineer',
    location: 'Bangalore, IN',
    salary: '₹18–30 LPA',
    type: 'Full-time',
    eligibility: '2–6 years, React/Next.js',
    applicationDates: 'Sep 18 – Nov 10, 2025',
    qualification: 'B.E/B.Tech',
    applyUrl: 'https://www.amazon.jobs/',
  },
  {
    id: 'amz04',
    company: 'Amazon',
    role: 'Data Engineer',
    location: 'Hyderabad, IN',
    salary: '₹20–34 LPA',
    type: 'Full-time',
    eligibility: '3–7 years, SQL, Python, Spark',
    applicationDates: 'Sep 22 – Nov 15, 2025',
    qualification: 'B.E/B.Tech',
    applyUrl: 'https://www.amazon.jobs/',
  },
  {
    id: 'sw01',
    company: 'Swiggy',
    role: 'Data Scientist',
    location: 'Bangalore, IN',
    salary: '₹20–32 LPA',
    type: 'Full-time',
    eligibility: '2–5 years, ML + Python',
    applicationDates: 'Sep 10 – Oct 25, 2025',
    qualification: 'Masters preferred',
    applyUrl: 'https://careers.swiggy.com/',
  },
  {
    id: 'sw02',
    company: 'Swiggy',
    role: 'iOS Engineer',
    location: 'Bangalore, IN',
    salary: '₹18–28 LPA',
    type: 'Full-time',
    eligibility: '2–5 years, Swift/SwiftUI',
    applicationDates: 'Sep 14 – Oct 25, 2025',
    qualification: 'B.E/B.Tech',
    applyUrl: 'https://careers.swiggy.com/',
  },
  {
    id: 'zi01',
    company: 'Zomato',
    role: 'UI/UX Designer',
    location: 'Gurugram, IN',
    salary: '₹12–20 LPA',
    type: 'Full-time',
    eligibility: 'Portfolio + Figma',
    applicationDates: 'Sep 05 – Oct 10, 2025',
    qualification: 'Any degree with portfolio',
    applyUrl: 'https://www.zomato.com/careers',
  },
  {
    id: 'zi02',
    company: 'Zomato',
    role: 'Android Engineer',
    location: 'Gurugram, IN',
    salary: '₹14–22 LPA',
    type: 'Full-time',
    eligibility: 'Kotlin/Compose',
    applicationDates: 'Sep 16 – Oct 20, 2025',
    qualification: 'B.E/B.Tech',
    applyUrl: 'https://www.zomato.com/careers',
  },
  {
    id: 'tcs01',
    company: 'TCS',
    role: 'Graduate Trainee',
    location: 'Multiple, IN',
    salary: '₹3.5–5.5 LPA',
    type: 'Full-time',
    eligibility: '2024/2025 passouts',
    applicationDates: 'Aug 20 – Sep 30, 2025',
    qualification: 'B.E/B.Tech/BSc/BCA',
    applyUrl: 'https://www.tcs.com/careers',
  },
  {
    id: 'tcs02',
    company: 'TCS',
    role: 'Java Developer',
    location: 'Chennai, IN',
    salary: '₹5–10 LPA',
    type: 'Full-time',
    eligibility: '1–4 years, Java/Spring',
    applicationDates: 'Sep 10 – Oct 15, 2025',
    qualification: 'B.E/B.Tech/MCA',
    applyUrl: 'https://www.tcs.com/careers',
  },
  {
    id: 'tcs03',
    company: 'TCS',
    role: 'QA Engineer',
    location: 'Pune, IN',
    salary: '₹4–8 LPA',
    type: 'Full-time',
    eligibility: 'Manual + Automation',
    applicationDates: 'Sep 12 – Oct 22, 2025',
    qualification: 'B.E/B.Tech/MCA',
    applyUrl: 'https://www.tcs.com/careers',
  },
  {
    id: 'inf01',
    company: 'Infosys',
    role: 'System Engineer',
    location: 'Pune, IN',
    salary: '₹4–6.5 LPA',
    type: 'Full-time',
    eligibility: '2024/2025 passouts',
    applicationDates: 'Sep 01 – Oct 10, 2025',
    qualification: 'B.E/B.Tech/MCA',
    applyUrl: 'https://www.infosys.com/careers',
  },
  {
    id: 'inf02',
    company: 'Infosys',
    role: 'React Developer',
    location: 'Hyderabad, IN',
    salary: '₹6–11 LPA',
    type: 'Full-time',
    eligibility: '1–4 years, React/Redux',
    applicationDates: 'Sep 08 – Oct 18, 2025',
    qualification: 'B.E/B.Tech/MCA',
    applyUrl: 'https://www.infosys.com/careers',
  },
  {
    id: 'inf03',
    company: 'Infosys',
    role: 'Business Analyst',
    location: 'Bengaluru, IN',
    salary: '₹8–13 LPA',
    type: 'Full-time',
    eligibility: '2–5 years, Agile, Stakeholder mgmt',
    applicationDates: 'Sep 18 – Oct 25, 2025',
    qualification: 'MBA preferred',
    applyUrl: 'https://www.infosys.com/careers',
  },
];

export function searchByRole(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return jobs.filter((j) => j.role.toLowerCase().includes(q));
}

export function searchByCompany(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return jobs.filter((j) => j.company.toLowerCase().includes(q));
}

export function getCompaniesForRole(query) {
  return searchByRole(query)
    .reduce((map, j) => {
      const key = j.company;
      if (!map[key]) map[key] = [];
      map[key].push(j);
      return map;
    }, {});
}

export function getRolesForCompany(query) {
  return searchByCompany(query)
    .reduce((map, j) => {
      const key = j.role;
      if (!map[key]) map[key] = [];
      map[key].push(j);
      return map;
    }, {});
}

